### ISSUE TITLE
only see the last 7 bookmarks

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/content-bookmarks#22] opened 2023-07-10 07:10 UTC
Hi, in community.humhub.com I have bookmarked a lot of posts over the last few years. At "My profile" > bookmarks it was possible to scroll through all of them (once at the bottom the next posts were loaded).

But now I can only see the last 7 posts. It seems the "endless scrolling" doesn’t work anymore.

A workaround is to filter the contents by end date to see older ones. But still only 7 posts are shown.

**Comment by yurabakhtin** [comment] 2023-07-10 11:57
@felixhahnweilheim Hello, I cannot reproduce this on community.humhub.com on my profile.
Do you see some errors when scroll down the bookmarks page?

**Comment by luke-** [comment] 2023-07-10 12:16
Probably this is related to this problem which occurs currently on the Community
https://github.com/humhub/wiki/issues/272

**Comment by luke-** [comment] 2023-07-10 14:49
Just merged. 

@felixhahnweilheim Can you please test this behavior on our Community again?

**Closed** 2023-07-10 15:15 UTC
Labels: bug
